
package pa.minipigs.Vista;

import pa.minipigs.Control.ControlVista;

/**
 * Panel de la interfaz gráfica encargado de realizar la búsqueda
 * y visualización de MiniPigs registrados en el sistema.
 *
 * Este panel permite al usuario ingresar un parámetro de búsqueda
 * y seleccionar el tipo de criterio (código, nombre, microchip,
 * raza, color, peso o altura). Los resultados se muestran en una
 * tabla que permite visualizar, modificar o eliminar registros.
 *
 * Las acciones generadas en este panel son gestionadas por
 * el controlador de la vista.
 *
 * @author Valen Aguilar
 */
public class PanelBuscar extends javax.swing.JPanel {
    /** Referencia al controlador encargado de gestionar los eventos de la vista. */
    private ControlVista controlVista;
    
    /**
    * Constructor del panel de búsqueda de MiniPigs.
    *
    * Inicializa los componentes gráficos del panel y establece la
    * referencia al controlador de la vista que gestionará las acciones
    * generadas por el usuario.
    *
    * @param controlVista controlador encargado de manejar los eventos
    * de la interfaz gráfica.
    */
    public PanelBuscar(ControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2EncontrarMP = new javax.swing.JButton();
        jButton3Limpiar = new javax.swing.JButton();
        jButton1VolverPantallaPrincipal = new pa.minipigs.Vista.BotonRedondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBusqueda = new javax.swing.JTable();
        jComboBoxTipoBusqueda = new javax.swing.JComboBox<>();
        jTextFieldParametroBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new PanelFondo("Imgs/3BuscarMiniPig.png");

        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setName("PantallaPrincipal"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2EncontrarMP.setBackground(new java.awt.Color(255, 231, 249));
        jButton2EncontrarMP.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jButton2EncontrarMP.setForeground(new java.awt.Color(51, 51, 51));
        jButton2EncontrarMP.setText("Encontrar MiniPigs");
        jButton2EncontrarMP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2EncontrarMP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton2EncontrarMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 195, 245, 50));

        jButton3Limpiar.setBackground(new java.awt.Color(255, 231, 249));
        jButton3Limpiar.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jButton3Limpiar.setForeground(new java.awt.Color(51, 51, 51));
        jButton3Limpiar.setText("Limpiar");
        jButton3Limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton3Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 195, 245, 50));

        jButton1VolverPantallaPrincipal.setBackground(new java.awt.Color(255, 204, 255));
        jButton1VolverPantallaPrincipal.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButton1VolverPantallaPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\MiniPigs\\Imgs\\Flechas\\FlechaAtras.png")); // NOI18N
        jButton1VolverPantallaPrincipal.setToolTipText("");
        jButton1VolverPantallaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1VolverPantallaPrincipal.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1VolverPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VolverPantallaPrincipalActionPerformed(evt);
            }
        });
        add(jButton1VolverPantallaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jTableBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jTableBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 204), null, null));
        jTableBusqueda.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jTableBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jTableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Ver Datos", "Modificar", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBusqueda.setGridColor(new java.awt.Color(255, 204, 255));
        jTableBusqueda.setMaximumSize(new java.awt.Dimension(300, 80));
        jTableBusqueda.setMinimumSize(new java.awt.Dimension(300, 80));
        jScrollPane1.setViewportView(jTableBusqueda);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 860, 390));

        jComboBoxTipoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipoBusqueda.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jComboBoxTipoBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombre", "ID MicroChip", "Raza", "Color", "Peso", "Altura" }));
        jComboBoxTipoBusqueda.setSelectedIndex(-1);
        jComboBoxTipoBusqueda.setToolTipText("");
        add(jComboBoxTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 89, 370, 34));

        jTextFieldParametroBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldParametroBusqueda.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jTextFieldParametroBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldParametroBusqueda.setCaretColor(new java.awt.Color(255, 204, 204));
        jTextFieldParametroBusqueda.setDragEnabled(true);
        jTextFieldParametroBusqueda.setName(""); // NOI18N
        add(jTextFieldParametroBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 141, 290, 34));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1VolverPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VolverPantallaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1VolverPantallaPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1VolverPantallaPrincipal;
    public javax.swing.JButton jButton2EncontrarMP;
    public javax.swing.JButton jButton3Limpiar;
    public javax.swing.JComboBox<String> jComboBoxTipoBusqueda;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableBusqueda;
    public javax.swing.JTextField jTextFieldParametroBusqueda;
    // End of variables declaration//GEN-END:variables
}
