
package pa.minipigs.Vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import pa.minipigs.Control.ControlVista;

/**
 * Panel de la interfaz gráfica encargado de mostrar y permitir la
 * modificación de la información de un MiniPig.
 * 
 * En este panel el usuario puede visualizar y editar los datos
 * asociados a un MiniPig, tales como nombre, género, raza, color,
 * peso, altura y características. También permite cambiar la foto
 * asociada al animal.
 * 
 * Las acciones generadas por los botones son gestionadas por
 * el controlador de la vista.
 * 
 * @author Valen Aguilar
 */

public class PanelIngresar extends javax.swing.JPanel {
    /** Referencia al controlador encargado de gestionar los eventos de la vista. */
    private ControlVista controlVista;
    
    /**
    * Constructor del panel de modificación y visualización de MiniPigs.
    * Inicializa los componentes gráficos del panel y establece la
    * referencia al controlador de la vista.
    *
    * @param controlVista controlador que gestiona las acciones
    * generadas en la interfaz gráfica.
    */
    public PanelIngresar(ControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
        
    }
    
    /**
     * Carga y muestra una imagen escalada en el JLabel fotoMiniPig.
     * Utiliza el tamaño actual del JLabel o su tamaño preferido si aún no ha sido renderizado.
     *
     * @param url ruta del archivo de imagen a mostrar
     */
    public void ponerImagen(String url) {
        if (url == null || url.trim().isEmpty()) {
            return;
        }
        try {
            java.io.File archivo = new java.io.File(url);
            if (!archivo.exists()) {
                return;
            }
            ImageIcon icon = new ImageIcon(url);
            int ancho = fotoMiniPig.getWidth();
            int alto = fotoMiniPig.getHeight();
            if (ancho <= 0 || alto <= 0) {
                ancho = fotoMiniPig.getPreferredSize().width;
                alto = fotoMiniPig.getPreferredSize().height;
            }
            if (ancho <= 0 || alto <= 0) {
                ancho = 220;
                alto = 210;
            }
            Image img = icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            fotoMiniPig.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            // Image could not be loaded, leave the label without an icon
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3IngresarNuevoMiniPig = new javax.swing.JButton();
        jButton1VolverSiNoIngresar = new pa.minipigs.Vista.BotonRedondo();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        idMicroChip = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        caracteristica1 = new javax.swing.JTextField();
        caracteristica2 = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        raza = new javax.swing.JTextField();
        URL = new javax.swing.JTextField();
        jButton2CambiarFoto = new javax.swing.JButton();
        fotoMiniPig = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new PanelFondo("Imgs/2ModificarMiniPig.png");

        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setName("PantallaPrincipal"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3IngresarNuevoMiniPig.setBackground(new java.awt.Color(255, 231, 249));
        jButton3IngresarNuevoMiniPig.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jButton3IngresarNuevoMiniPig.setForeground(new java.awt.Color(51, 51, 51));
        jButton3IngresarNuevoMiniPig.setText("Ingresar");
        jButton3IngresarNuevoMiniPig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3IngresarNuevoMiniPig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton3IngresarNuevoMiniPig, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 563, 245, 65));

        jButton1VolverSiNoIngresar.setBackground(new java.awt.Color(255, 204, 255));
        jButton1VolverSiNoIngresar.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButton1VolverSiNoIngresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\MiniPigs\\Imgs\\Flechas\\FlechaAtras.png")); // NOI18N
        jButton1VolverSiNoIngresar.setToolTipText("");
        jButton1VolverSiNoIngresar.setActionCommand("Volver PantallaPrincipal");
        jButton1VolverSiNoIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1VolverSiNoIngresar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1VolverSiNoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VolverSiNoIngresarActionPerformed(evt);
            }
        });
        add(jButton1VolverSiNoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        codigo.setForeground(new java.awt.Color(51, 51, 51));
        codigo.setCaretColor(new java.awt.Color(255, 204, 204));
        codigo.setDragEnabled(true);
        codigo.setName(""); // NOI18N
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 76, 360, 34));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setCaretColor(new java.awt.Color(255, 204, 204));
        nombre.setDragEnabled(true);
        nombre.setName(""); // NOI18N
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 133, 360, 34));

        genero.setBackground(new java.awt.Color(255, 255, 255));
        genero.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        genero.setForeground(new java.awt.Color(51, 51, 51));
        genero.setCaretColor(new java.awt.Color(255, 204, 204));
        genero.setDragEnabled(true);
        genero.setName(""); // NOI18N
        add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 360, 34));

        idMicroChip.setBackground(new java.awt.Color(255, 255, 255));
        idMicroChip.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        idMicroChip.setForeground(new java.awt.Color(51, 51, 51));
        idMicroChip.setCaretColor(new java.awt.Color(255, 204, 204));
        idMicroChip.setDragEnabled(true);
        idMicroChip.setName(""); // NOI18N
        add(idMicroChip, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 246, 290, 34));

        altura.setBackground(new java.awt.Color(255, 255, 255));
        altura.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        altura.setForeground(new java.awt.Color(51, 51, 51));
        altura.setCaretColor(new java.awt.Color(255, 204, 204));
        altura.setDragEnabled(true);
        altura.setName(""); // NOI18N
        add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 473, 360, 34));

        caracteristica1.setBackground(new java.awt.Color(255, 255, 255));
        caracteristica1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        caracteristica1.setForeground(new java.awt.Color(51, 51, 51));
        caracteristica1.setCaretColor(new java.awt.Color(255, 204, 204));
        caracteristica1.setDragEnabled(true);
        caracteristica1.setName(""); // NOI18N
        add(caracteristica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 290, 34));

        caracteristica2.setBackground(new java.awt.Color(255, 255, 255));
        caracteristica2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        caracteristica2.setForeground(new java.awt.Color(51, 51, 51));
        caracteristica2.setCaretColor(new java.awt.Color(255, 204, 204));
        caracteristica2.setDragEnabled(true);
        caracteristica2.setName(""); // NOI18N
        add(caracteristica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 588, 290, 34));

        peso.setBackground(new java.awt.Color(255, 255, 255));
        peso.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        peso.setForeground(new java.awt.Color(51, 51, 51));
        peso.setCaretColor(new java.awt.Color(255, 204, 204));
        peso.setDragEnabled(true);
        peso.setName(""); // NOI18N
        add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 417, 360, 34));

        color.setBackground(new java.awt.Color(255, 255, 255));
        color.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        color.setForeground(new java.awt.Color(51, 51, 51));
        color.setCaretColor(new java.awt.Color(255, 204, 204));
        color.setDragEnabled(true);
        color.setName(""); // NOI18N
        add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 361, 360, 34));

        raza.setBackground(new java.awt.Color(255, 255, 255));
        raza.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        raza.setForeground(new java.awt.Color(51, 51, 51));
        raza.setCaretColor(new java.awt.Color(255, 204, 204));
        raza.setDragEnabled(true);
        raza.setName(""); // NOI18N
        add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 304, 360, 34));

        URL.setEditable(false);
        URL.setBackground(new java.awt.Color(255, 255, 255));
        URL.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        URL.setForeground(new java.awt.Color(51, 51, 51));
        URL.setCaretColor(new java.awt.Color(255, 204, 204));
        URL.setDragEnabled(true);
        URL.setName(""); // NOI18N
        add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 407, 240, 25));

        jButton2CambiarFoto.setBackground(new java.awt.Color(255, 153, 153));
        jButton2CambiarFoto.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jButton2CambiarFoto.setForeground(new java.awt.Color(51, 51, 51));
        jButton2CambiarFoto.setText("Ingresar Foto");
        jButton2CambiarFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2CambiarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton2CambiarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 435, 240, 40));
        add(fotoMiniPig, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 140, 220, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\MiniPigs\\Imgs\\2ModificarMiniPig.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1VolverSiNoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VolverSiNoIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1VolverSiNoIngresarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField URL;
    public javax.swing.JTextField altura;
    public javax.swing.JTextField caracteristica1;
    public javax.swing.JTextField caracteristica2;
    public javax.swing.JTextField codigo;
    public javax.swing.JTextField color;
    private javax.swing.JLabel fotoMiniPig;
    public javax.swing.JTextField genero;
    public javax.swing.JTextField idMicroChip;
    public javax.swing.JButton jButton1VolverSiNoIngresar;
    public javax.swing.JButton jButton2CambiarFoto;
    public javax.swing.JButton jButton3IngresarNuevoMiniPig;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField nombre;
    public javax.swing.JTextField peso;
    public javax.swing.JTextField raza;
    // End of variables declaration//GEN-END:variables
}
