
package pa.minipigs.Vista;

/**
 * Representa la ventana principal de la aplicación MiniPigs.
 * 
 * Esta clase extiende JFrame y actúa como contenedor principal
 * donde se cargan los diferentes paneles de la interfaz gráfica
 * (panel principal, búsqueda, modificación, créditos, etc.).
 * 
 * La gestión del contenido mostrado en esta ventana es realizada
 * por el controlador de la vista.
 * 
 * @author Valen Aguilar
 */
public class Ventana extends javax.swing.JFrame {

    /**
    * Constructor de la ventana principal.
    * Inicializa los componentes gráficos de la interfaz.
    */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniPigs");
        setBackground(new java.awt.Color(255, 204, 204));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setName("MiniPigs"); // NOI18N
        setSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("MiniPigs");
        getAccessibleContext().setAccessibleDescription("MiniPigs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
