spring.application.name=micro-servicios-juguetes
server.port=8090

server.servlet.context-path=/juguete

spring.datasource.url=jdbc:mysql://localhost:3306/microservicios
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true